### ISSUE TITLE
502 after starting wiki.js in normal mode on Debian 9 (stretch)

### ISSUE THREAD

**Issue by messerbill** [Requarks/wiki-v1#137]
### Actual behavior
Running wiki via `node wiki configure xxx` is working fine. After finishing the wizard wiki wants to restart and afterwards it leads into `502 Bad Gateway`. Even starting wiki using `pm2` or `node wiki start` leads into `502`. The error from the pm2 logs said nothing but how to use the start commad.....wiki's logs are empty.

### Expected behavior
Wiki should be available after startup...

### Steps to reproduce the behavior

- Use Debian 9 (stretch)
- Use node -v `v10.10.0`
- Use nginx as reverse proxy
- Start config via `node wiki configure myPort`
- Open Browser and navigate to wiki
- Do all the steps in the wizard
- let wiki restart itself
- wonder about the appearing `502`

Like i said above, it makes no difference how i start the wiki. Configuring is always working, normal mode is never working.

**Comment by nidhi-nair** [comment]
Hi @EthanRBrown

This might be a little out of context  for you at this point, but what were you using port 80 for initially? I have currently configured wikijs to listen on 8080 to no avail.

**Comment by EthanRBrown** [comment]
Hi, @nidhi-nair,

Yup, it's been a long time since I was dealing with this.  If I recall correctly, wiki.js runs by default on port 80.  As I'm sure you know, running on a port less than 1024 requires elevated permissions, so I'm pretty sure that this problem was related to permissions somehow, but I never did find out what the specific issue was.  The _nice_ thing about running on port 80 (or 443 if you're rocking HTTPS) is that you don't need to specify the port when accessing with a browser.

**Comment by messerbill** [comment]
The current version works as expected after reinstalling wiki.js - i neither ran into any problems in interactive nor in configure mode...I can also imagine that my PM2 messed this up hence why I also reinstalled PM2. So i guess that this can be closed

**Comment by kemeny** [comment]
After node wiki configuration I would get same 502. Changing in to port 3000  fixed the issue on ubuntu.
